### ISSUE TITLE
ToDo: Implement "Away From Home" mode

### ISSUE THREAD

**Issue by yelloish6** [yelloish6/Agamemnon#3]
Create a button in the main interface to set an AFH ("Away From Home") mode active: features of the AFH:
- [ ] macro that turns lights on randomly throuhout the house
- [ ] set the heating system to away mode
- [ ] record movement on all cameras
- [ ] close garage door
